apiVersion: v1 
kind: Service
metadata: 
  name: database
  labels:
    role: frontend
    env: demo
spec: 
   type: LoadBalancer
   ports: 
    - protocol: TCP
      port: 3000
   selector:     
    role: frontend