name: 'Build & Deploy Helm chart to EKS'
on:
  push:
    branches:
      - master
env:
  account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  EKS_CLUSTER: ${{ secrets.EKS_CLUSTER }}
  EKS_REGION: ${{ secrets.EKS_REGION }}
 
jobs:
  backend:
    name: BUILD 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/job-management-service
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: build image 
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/backend:2
    - name: docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:2
  
 
  frontend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-ui

    # strategy:
    #   matrix:
    #     node-version: [15.x]
   
    #steps:
    # - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build

      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: build image 
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/frontend:3
      - name: docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:3
  
  deploy:
    runs-on: ubuntu-latest
    needs:
    - frontend
    - backend 
    steps: 
      - uses: actions/checkout@v2

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: connect to EKS cluster
        run: aws eks --region $EKS_REGION update-kubeconfig --name $EKS_CLUSTER

      - name: deploy
        uses: scalive/github-action-eks-helm@master
      - name: helm deployment
        run: helm upgrade -i greencommits  main