apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image1.repository }}:{{ .Values.image1.tag }}"
        env: 
         - name: BASE_URL
           value: http://ac0eef5b0442d476b9e11c48ba2b67f5-1107593635.ap-south-1.elb.amazonaws.com:8080
        value: 
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dd
  labels:
    app: pg
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pg 
  template:
    metadata:
      labels:
        app: pg 
    spec:
      containers:
      - name: pg 
        image: "{{ .Values.image2.repository }}:{{ .Values.image2.tag }}"
        env:
          - name: POSTGRES_USER
            value: {{ .Values.secert1.Postgres_user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.secert1.Postgres_passwd }} 
          - name: POSTGRES_DB
            value: {{ .Values.secert1.Postgres_db }}
        ports:
          - name: http
            containerPort: 5432
            protocol: TCP
       
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bc
  labels:
    app: back 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: back 
  template:
    metadata:
      labels:
        app: back 
    spec:
      containers:
      - name: back
        image: "{{ .Values.image3.repository }}:{{ .Values.image3.tag }}"
        env:
          - name: SPRING_DATASOURCE_URL
            value: {{ .Values.secert2.jobs_url }}
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.secert2.jobs_usr }} 
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.secert2.jobs_passwd }}
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: {{ .Values.secert2.jobs_update }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP


   
