apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    role: pg
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pg
  template:
    metadata:
      labels:
        role: pg
    spec:
      containers:
      - name: pg
        image: dhanrajnath/postgres:latest
        env:
        - name: POSTGRES_USER
          value: jobs_usr
        - name: POSTGRES_PASSWORD
          value: us3rs
        - name:  POSTGRES_DB
          value: jobs
        ports:
        - containerPort: 5432